name: 'Dummy Custom Actions'
description: 'Testing custom action'
inputs:
  num1:
    description: 'First Number'
    required: true
  num2:
    description: 'Second Number'
    required: true
#   bucket-region:
#     description: 'S3 bucket region name'
#     required: false
#     default: us-east-1
#   dist-folder:
#     description: 'The folder containing the deployable files'
#     required: true
outputs:
  sum:
    description: 'Sum of numbers'
runs:
  using: 'docker'
  image: 'Dockerfile'